// <auto-generated />
using System;
using DynamicPlugins.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DynamicPlugins.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191118030551_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DynamicPlugins.Models.Plugin", b =>
                {
                    b.Property<Guid>("PluginId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Name");

                    b.Property<string>("UniqueKey");

                    b.Property<string>("Version");

                    b.HasKey("PluginId");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("DynamicPlugins.Models.PluginMigration", b =>
                {
                    b.Property<Guid>("PluginMigrationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Down");

                    b.Property<Guid>("PluginId");

                    b.Property<string>("Up");

                    b.Property<string>("Version");

                    b.HasKey("PluginMigrationId");

                    b.ToTable("PluginMigrations");
                });
#pragma warning restore 612, 618
        }
    }
}
